### PR TITLE
BREAKING CHANGE: change course and allow execution of scripts in node_modules

### LINKED ISSUE #74: Readme generator cannot generate a URL for a non-tag, non-master branch
### Please describe the bug

Pass in `some-random-branch` into `processDocs` to select a non-master branch and it assumes you're trying to use a release tag instead of generating a path leading to that file on your branch.

### Reproducing the error

None

### Expected behavior

Readme URL generator should accept branches AND tags of all types. `master`, `development` and `v1.0.0` should all be handled properly

### What browsers are you seeing the problem on?

_No response_

### Additional context

_No response_

### Exit criteria

_No response_

### PR DESCRIPTION
**Pull request by DukeFerdinand**
# Alaska Airlines Pull Request

`v2.10.1` and other changes to the library did _not_ go as planned. This semi-reverts the "import and run functions" plan we had before, while keeping all of the code more or less in tact.

### The game plan now is:
- Developer upgrades to `3.x.x` and they have to do _literally nothing_ to get their build script running
- If a developer is working on a non-standard repository, we support that too. The developer can just import functions from files and setup their own custom build tooling (should be used sparingly - probably JUST auro-form for now)
- If a developer needs to _extend_ based functionality of some scripts, that's also feasible, but the changes should be upstreamed if they will affect more than one component.

### New file and what they mean:
- `scripts/utils/sharedFileProcessorUtils.mjs` is a new file that contains every single export (outside of Logger) that a developer needs to import in order to synchronize or compile local files. This is the backbone of the new processor concept below. 
- `scripts/builds/processors/*` - these new "processors" are the default expected features a developer wants to see when running `build:docs` or `sync:config` (command name TBD). They build on `sharedFileProcessorUtils` functions, and re-export some sensible file preset like `README.md`, `demo/index.md` and `demo/api.md` depending on the use case, as well as a simple loop to process each file using shared utilities.
- `scripts/builds/generateDocs & scripts/builds/syncGithubFiles` - these are pre-configured scripts that a developer will use to run the above processors. They are intended to be run directly using the file paths already present in a given component's `package.json` (where applicable). Please note - _these scripts are NOT INTENDED to be imported, **modified**, and run with custom adaptations_.
  - If you need custom processing or need to update the build script in a non-breaking way, open a PR and modify the source `scripts/builds/processors/*` processor directly.
  - Alternatively, take a look at the same `scripts/builds/processors/*` files and import the desired functions from `scripts/utils/sharedFileProcessorUtils.mjs` in a new file inside your repository (`import {whateverFunction} from '@aurodesignsystem/auro-library/scripts/utils/sharedFileProcessorUtils.mjs'`)

Closes #74  

## Before Submitting this pull request:
- Link all tickets in this repository related to this PR in the `Development` section
_note: all pull requests require at least one linked ticket_
- If this PR is `Ready For Review`, all ticket's linked under `Development` must have their status changed to `Ready For Review` as well

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license and I have performed a self-review of my own update.**

## Summary by Sourcery

Update the function API to support fetching README files from any specified branch or tag, enhancing flexibility for users. Refactor the processDocs API to use a more intuitive configuration object. Add comprehensive tests to cover the new functionality and ensure robustness.

New Features:
- Allow users to specify any branch or tag for fetching README files, not just 'master' or version tags.

Enhancements:
- Refactor the processDocs API to accept a configuration object with named keys instead of unnamed arguments.

Tests:
- Add tests for the new functionality of generating README URLs from branches other than 'master'.
- Introduce tests for the AuroTemplateFiller class to ensure correct template value replacements.

## Summary by Sourcery

Revert previous changes to the script execution plan, allowing execution of scripts in node_modules. Introduce new utilities and processors for file synchronization and documentation generation, enhancing flexibility and usability. Add tests and documentation for the new features and refactorings.

New Features:
- Introduce a new file 'scripts/utils/sharedFileProcessorUtils.mjs' that contains essential exports for developers to synchronize or compile local files, supporting custom build tooling.

Enhancements:
- Refactor the processDocs API to use a more intuitive configuration object, improving the flexibility and usability of the documentation generation process.

Documentation:
- Add comprehensive documentation for the new file processing utilities and processors, explaining their purpose and usage.

Tests:
- Introduce tests for the new functionality of generating README URLs from branches other than 'master'.
- Add tests for the AuroTemplateFiller class to ensure correct template value replacements.

### CODE REVIEW

File: scripts/build/generateDocs.mjs [hunk 1]
```diff
@@ -105,8 +105,16 @@ export function generateReadmeUrl(tag = 'master', variantOverride = '') {
   }
 
   const baseRepoUrl = 'https://raw.githubusercontent.com/AlaskaAirlines/WC-Generator'
-  if (tag !== 'master') {
-    return `${baseRepoUrl}/refs/tags/${tag}/componentDocs/README` + variantString + '.md';
+
+  // check if tag starts with 'vX' since our tags are `v4.0.0`
+  const isTag = /^v\d.*$/.test(branchOrTag);
```
[the remark this answers is not in the document]
Comment (DukeFerdinand) [reply scripts/build/generateDocs.mjs:110]: this is a great catch! I wanted to leave open the `startsWith('v')` as our branch names are `<first-initial><lastname>/<feature>` in case someone has a `v` name but your combination regex + startsWith handles both

File: scripts/build/generateDocs.mjs [hunk 2]
```diff
@@ -240,13 +249,23 @@ export async function processContentForFile(config) {
...
 /**
  *
- * @param {string} remoteReadmeVersion - the release version tag to use instead of master
- * @param {string} [readmeVariant] - the release version tag to use instead of master
+ * @param {ProcessorConfig} config - the configuration for this processor
  * @return {Promise<void>}
  */
-export async function processDocFiles(remoteReadmeVersion = 'master', readmeVariant = undefined) {
+export async function processDocFiles(config) {
+  const { overwriteLocalCopies = true, remoteReadmeVersion = "master", readmeVariant = "" } = config;
```
Comment (jason-capsule42) [inline scripts/build/generateDocs.mjs:267]:
```suggestion
  const { overwriteLocalCopies = true, remoteReadmeVersion = "master", readmeVariant = "esm" } = config;
```

File: scripts/build/generateDocs.mjs [hunk 3]
```diff
@@ -105,8 +105,17 @@ export function generateReadmeUrl(tag = 'master', variantOverride = '') {
   }
 
   const baseRepoUrl = 'https://raw.githubusercontent.com/AlaskaAirlines/WC-Generator'
-  if (tag !== 'master') {
-    return `${baseRepoUrl}/refs/tags/${tag}/componentDocs/README` + variantString + '.md';
+
+  // check if tag starts with 'vX' since our tags are `v4.0.0`
+  const isTag = branchOrTag.startsWith('v') &&
+    /^\d+\.\d+\.\d+(-.*)?$/.test(branchOrTag.slice(1));
```
Comment (jason-capsule42) [inline scripts/build/generateDocs.mjs:111]: Consider adding a test for handling non main branch releases (e.g. `-beta.1`)

**Review by jason-capsule42 — CHANGES_REQUESTED** [review]

**Comment by DukeFerdinand** [comment]
@sourcery-ai review

File: scripts/build/generateDocs.mjs (hunk 3 above)
Comment (DukeFerdinand) [reply scripts/build/generateDocs.mjs]: this is covered in the new work!

File: scripts/build/generateDocs.mjs (hunk 2 above)
Comment (DukeFerdinand) [reply scripts/build/generateDocs.mjs]: this is addressed in the new work!

File: scripts/utils/auroLibraryUtils.mjs
Comment (jason-capsule42) [inline scripts/utils/auroLibraryUtils.mjs:1]: Does this script make more sense to be in the build dir?

**Review by jason-capsule42 — CHANGES_REQUESTED** [review]
Please resolve all Sourcery feedback

File: scripts/utils/sharedFileProcessorUtils.mjs [hunk 4]
```diff
@@ -0,0 +1,257 @@
...
+/**
+ * Process the content of a file.
+ *
+ * This is a high level function that performs the following via lower functions:
+ * - Read contents of file
+ * - Run "markdown-magic" on file contents (optional, *.md specific)
+ * - Run template variable replacement on file contents
+ * @param {FileProcessorConfig} config - the config for this file
+ */
+export async function processContentForFile(config) {
```
[the remark this answers is not in the document]
Comment (DukeFerdinand) [reply scripts/utils/sharedFileProcessorUtils.mjs:219]: hmm this proposed function doesn't work in the same way as my current function. you never write the remote file to disk (see retrieveRemoteFileCopy function) so the local template will never be updated even if the local copy doesn't exist

[the remark this answers is not in the document]
Comment (DukeFerdinand) [reply scripts/utils/sharedFileProcessorUtils.mjs:219]: this looks a lot like what I already have, so I'm going to say it's good to go for now

File: scripts/utils/auroLibraryUtils.mjs
Comment (DukeFerdinand) [reply scripts/utils/auroLibraryUtils.mjs:1]: I renamed the projectRoot method in here to better reflect how it can be used anywhere :)

I don't think it should live in the build directory tbh. that scripts/build directory is getting too cluttered. we may want to enforce a "scripts only" policy in there so you know you can run any of those as an actual node script.

**Review by jason-capsule42 — APPROVED** [review]
